### ISSUE TITLE
Audio source selection

### ISSUE THREAD

**Issue by nicolharico** [kyunwang/pitch-analyser#2]
Hi,
First of all, thanks for this lib which is working pretty smoothly !
I'm converting my c# wpf apps in electronJs with angular6, and I would have to not only detect pitch from audio, but more importantly be able to choose the audio input I'll be listening to (I'll have multiple soundcards).

Is there any easy way to implement this kind of feature ?

Cheers,
Nicolas

**Comment by kyunwang** [comment]
Great to hear it is working out for you!

Not too clear with soundcards so 😅 just to be sure is what you need to be able to listen to multiple outputs simultaneously or is it that you want to select one audio input of many as you have multiple audiocards.

As of the moment  selecting one specific input is not possible, but I can look into it this weekend as it's pretty useful to have.

**Comment by nicolharico** [comment]
Thanks for your reply 🥇 

Right now, the use case I have is being able listen/pitch on a selected input (from a simple USB card) at a moment, then, few seconds later, being able to do the same on another audio input. Pretty simple and straight forward 👍 

I would have gladly proposed to contribute to your project but I'm not 100% at ease with javascript/node as I just started switching from C# to electronJs/angular !

Thanks in advance and let me know if I can help 👍

**Comment by kyunwang** [comment]
Hi, well it's weekend 🎊 so I looked into it for a bit. It seems like the default audio input is set by the system. I am on a mac so the default would be defined in the `Sound / input` tab in `System Preferences`.

I think I got what you need but would you be so kind to test it out for me?

You can get the release candidate with `npm install pitch-analyser@next`that should install the version `0.1.3-rc.1` with it.

The readme has yet to be updated, below I have added a temporary documentation for you.

And could you give me a nudge if everything works out? Then I can merge it into master and give a shout if you need a simple example.

## So what you will get now in the package:
- A new helper function is to help you get all the possible sound inputs of your system, namely `getInputDevices()`
- A new method added to the PitchAnalyser class, namely `changeInputDevice()`

## How to change the input
So here is how you can use it

### First get the pre build version to test 😉
Run `npm install pitch-analyser@next` in your favorite terminal
This should install version 0.1.3-rc.1

### Then import the new helper alongside PitchAnalyser
```
import PitchAnalyser, { getInputDevices } from 'pitch-analyser;
```

### Get the possible audio inputs
We will do this with the new helper function `getInputDevices`

```
// Will return a promise you can resolve like so... or use async / await
getInputDevices().then(devices => {
	devices.forEach(device => {
		// 'device' is an object
		// To change the input channel we listen to we need the device.deviceId
		// Do something here like creating an <select> html element with <options>
	});
});
```
You can save the output `device` somewhere like an array and render it to the front-end as an select with options or however you like 👍

### Change the audio input
Finally to the most important part, changing the audio input! 🔥

```
// The initialized analyser with given option
const analyser = new PitchAnalyser(options);

...


// Using the previous example of an select element with options
// The device.deviceId should be passed to the method
analyser.changeInputDevice(device.deviceId);

```

That's it!

**Comment by kyunwang** [comment]
Closed due to no response and inactivity. Message is not generated but written manually ;)
